#pragma once
#include "Global.h"
BOOL S_TCPSend(LPSOCKET_INFORMATION SOCKET_INFO);
BOOL S_UDPSend(LPSOCKET_INFORMATION SOCKET_INFO, SOCKADDR_IN * Server);
BOOL S_TCPRecieve(LPSOCKET_INFORMATION SOCKET_INFO, BOOL isCALLBACK);

BOOL S_UDPRecieve(LPSOCKET_INFORMATION SOCKET_INFO, BOOL isCALLBACK, DWORD * RecvBytes);
BOOL S_TCPConnect(SOCKET WritingSocket, SOCKADDR_IN * InternetAddr);
BOOL S_UDPConnect(SOCKET WritingSocket, SOCKADDR_IN * InternetAddr);
void UpdateTransmission(LPTRANSMISSION_INFORMATION TRANS_INFO, DWORD BytesRecieved, LPSOCKET_INFORMATION SOCKET_INFO);
void PrintTransmission(LPTRANSMISSION_INFORMATION TRANS_INFO);
long delay(SYSTEMTIME t1, SYSTEMTIME t2);